logging:
  level:
    org.jooq.tools: DEBUG

spring:
  application:
    name: Catalogist
  profiles:
    active: prod
  flyway:
    enabled: true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    execution:
      thread-name-prefix: catalogist-t-
    scheduling:
      thread-name-prefix: catalogist-s-
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      pool-name: Catalogist-DB
